print("Hello world!")
print("What is yur name? ")
myName = input()
print("It is good to meet you, "+ myName)
print("The lentgh of your name is: ")
print(len(myName))
print("What is your age: ")
myAge = input()
print(f'{myName.title()} you will be ' + str(int(myAge) + 1) + ' in a year.') 